# Generated by Django 4.0.5 on 2022-07-03 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('moeda', models.CharField(max_length=30)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
