# Generated by Django 4.0.5 on 2022-07-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao_grafico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precos',
            name='data',
            field=models.CharField(max_length=30),
        ),
    ]
